<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="java.util.Date"%>
<%@ page import="java.text.SimpleDateFormat"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>


<!DOCTYPE html>
<html>

<jsp:include page="/WEB-INF/views/include/metacssjs.jsp"></jsp:include>

<c:url value="/setLikeOrDislike" var="setLikeOrDislike"></c:url>

<body>

	<%-- <jsp:include page="/WEB-INF/views/loader.jsp"></jsp:include> --%>

	<!-- TAGS -->
	<jsp:include page="/WEB-INF/views/include/tags.jsp"></jsp:include>
	<!-- TAGS End -->


	<!-- Header -->
	<jsp:include page="/WEB-INF/views/include/header.jsp"></jsp:include>
	<!-- Header End -->
	<%-- <jsp:include page="/WEB-INF/views/include/menubar.jsp"></jsp:include> --%>
	<div class="head_marg">

		<!--main banner -->
		<%-- <div class="main_banner"
			style="background: url(${pageContext.request.contextPath}/resources/images/main_banner.jpg) no-repeat center top; background-size: cover;">
			<div class="banner_caption">
				<h3 class="banner_title">
					Just Launched <span>Can't wait to send surprises?</span>
				</h3>
				<p class="banner_txt">Choose Same Day Delivery Gifts</p>
				<a href="${pageContext.request.contextPath}/productlist"
					class="send_now_btn">Send Now</a>

				<!-- <form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_1eXaKykckwM8kP" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="50" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="4444444444444444444444444"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form> -->

				<a href="${pageContext.request.contextPath}/goToPay" id="11">Go
					to Pay</a>

				<button id="rzp-button2">Pay2</button>
				<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
				<script>
					var options = {
						"key" : "rzp_test_1eXaKykckwM8kP", // Enter the Key ID generated from the Dashboard
						"amount" : "50", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
						"currency" : "INR",
						"name" : "Acme Corp11",
						"description" : "Test Transaction11",
						"image" : "https://example.com/your_logo",
						"order_id" : "order_9A33XWu170gUtm", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
						"handler" : function(response) {
							alert(response.razorpay_payment_id);
							alert(response.razorpay_order_id);
							alert(response.razorpay_signature)
						},
						"prefill" : {
							"name" : "Gaurav Kumar",
							"email" : "gaurav.kumar@example.com",
							"contact" : "9999999999"
						},
						"notes" : {
							"address" : "Razorpay Corporate Office"
						},
						"theme" : {
							"color" : "#3399cc"
						}
					};
					var rzp1 = new Razorpay(options);
					rzp1.on('payment.failed', function(response) {
						alert(response.error.code);
						alert(response.error.description);
						alert(response.error.source);
						alert(response.error.step);
						alert(response.error.reason);
						alert(response.error.metadata.order_id);
						alert(response.error.metadata.payment_id);
					});
					document.getElementById('rzp-button2').onclick = function(e) {
						rzp1.open();
						e.preventDefault();
					}
				</script>
			</div>
		</div> --%>



		<!-- BANNER -->

		<%-- <c:forEach items="${bannerList}" var="banner">

			<div class="main_banner"
				style="background-image: url('${offerImgUrl}${banner.bannerImage}') no-repeat center top; background-size: cover;">
				<div class="banner_caption">
					<h3 class="banner_title">
						${banner.bannerEventName} <span>${banner.captionOnproductPage}</span>
					</h3>
					<a href="javascript:void(0)"
						onclick="openProductListPageByTags('${banner.tagIds}')"
						class="send_now_btn">Send Now</a>
				</div>
			</div>

		</c:forEach> --%>


		<section class="lazy slider" data-sizes="50vw">

			<c:forEach items="${bannerList}" var="banner">
				<a href="javascript:void(0)"
					onclick="openProductListPageByTags('${banner.tagIds}')"
					class="send_now_btn">
					<div class="main_banner"
						style="background: url('${offerImgUrl}${banner.bannerImage}<%-- ${offerImgUrl}${banner.bannerImage} --%>'),
					url('${pageContext.request.contextPath}/resources/images/no_img_folder/no-banner-image.jpg')
					  no-repeat center top; background-size: cover;">

						<div class="rotate-banner">
							<div class="banner_caption">
								<h3 class="banner_title">
									${banner.bannerEventName} <span>${banner.captionOnproductPage}</span>
								</h3>
								Send Now
							</div>
						</div>
					</div>
				</a>
			</c:forEach>



		</section>



		<script type="text/javascript">
			$(document).on('ready', function() {
				$(".lazy").slick({
					lazyLoad : 'ondemand', // ondemand progressive anticipated
					infinite : true,
					autoplay: true,
					  autoplaySpeed: 2000
				});
			});
			
			//Akhilesh
			/* $(window).load(function() {
				//alert("On Load")
			    $(".loader-Parent").fadeOut("slow");
			}) */
			
			$(window).on('load', function(){
				//alert("Ok")
  setTimeout(removeLoader, 2000); //wait for page load PLUS two seconds.
});
function removeLoader(){
    $( "#loadingDiv").fadeOut(500, function() {
      // fadeOut complete. Remove the loading div
      $( "#loadingDiv").remove(); //makes page more lightweight 
  });  
}

		</script>



	</div>

	<!-- STATIC -->

	<!-- multiple product boxes -->
	<div class="find_store">
		<div class="wrapper">
			<div class="prod_cat_bx">
				<div class="prod_cat_1">
					<div class="cakes_cat_1">
						<a
							href="${pageContext.request.contextPath}/showProductListCategory/1">
							<div class="img_cap">
								<img
									src="${pageContext.request.contextPath}/resources/images/cakes_1.jpg"
									alt="">
								<div class="prod_cat_cap">
									<span>Cakes</span>
								</div>
							</div>
						</a>
					</div>
				</div>
				<div class="prod_cat_2">
					<div class="divid_two">
						<div class="divide_one_pic left">
							<div class="single_pic">
								<a
									href="${pageContext.request.contextPath}/showProductListCategory/2">
									<img
									src="${pageContext.request.contextPath}/resources/images/offers_prod_1.jpg"
									alt="">
									<div class="prod_cat_cap1">
										<span>Pastries</span>
									</div>
								</a>
							</div>
						</div>
						<div class="divide_one_pic right">
							<div class="single_pic">
								<a
									href="${pageContext.request.contextPath}/showProductListCategory/3">
									<img
									src="${pageContext.request.contextPath}/resources/images/offers_prod_2.jpg"
									alt="">
									<div class="prod_cat_cap1">
										<span>Savories</span>
									</div>
								</a>
							</div>
						</div>
						<div class="clr"></div>
					</div>
					<div class="divid_two">
						<div class="divide_one_pic left">
							<div class="single_pic">
								<a
									href="${pageContext.request.contextPath}/showProductListCategory/9">
									<img
									src="${pageContext.request.contextPath}/resources/images/offers_prod_3.jpg"
									alt="">
									<div class="prod_cat_cap1">
										<span>Packaged Cakes</span>
									</div>
								</a>
							</div>
						</div>
						<div class="divide_one_pic right">
							<div class="single_pic">
								<a
									href="${pageContext.request.contextPath}/showProductListCategory/4">
									<img
									src="${pageContext.request.contextPath}/resources/images/offers_prod_4.jpg"
									alt="">
									<div class="prod_cat_cap1">
										<span>Chocolates</span>
									</div>
								</a>
							</div>
						</div>
						<div class="clr"></div>
					</div>
					<div class="single_prod">
						<div class="single_pic">
							<a
								href="${pageContext.request.contextPath}/showProductListCategory/8">
								<img
								src="${pageContext.request.contextPath}/resources/images/offers_prod_5.jpg"
								alt="">
								<div class="prod_cat_cap1">
									<span>Bakersware</span>
								</div>
							</a>

						</div>
					</div>
				</div>
				<div class="prod_cat_3">
					<div class="lst_tow marg_btm divice">
						<div class="single_pic">
							<a
								href="${pageContext.request.contextPath}/showProductListCategory/1">
								<img
								src="${pageContext.request.contextPath}/resources/images/combo_2.jpg"
								alt="">
								<div class="prod_cat_cap1">
									<span>Combo</span>
								</div>
							</a>
						</div>
					</div>
					<div class="lst_tow divice1">
						<div class="single_pic ">
							<a
								href="${pageContext.request.contextPath}/showProductListCategory/1">
								<img
								src="${pageContext.request.contextPath}/resources/images/combo_2.jpg"
								alt="">
								<div class="prod_cat_cap1">
									<span>Combo</span>
								</div>
							</a>
						</div>
					</div>
				</div>
				<div class="clr"></div>
			</div>
		</div>
	</div>





	<!-- multiple product boxes -->
	<%-- <div class="find_store">
		<div class="wrapper">
			<div class="prod_cat_bx">

				<c:forEach items="${frCatList}" var="frCat" varStatus="count">
					<div class="prod_cat_1">
						<div class="cakes_cat_1 new">
							<a
								href="${pageContext.request.contextPath}/filterCategoryProduct/${frCat.catId}">
								<div class="img_cap">
									<img
										src="https://d3s16h6oq3j5fb.cloudfront.net/img/Spinner-2.gif"
										class="lazy" data-src="${catImgUrl}${frCat.imageName}" alt="">
									<div class="prod_cat_cap">
										<span>${frCat.catName}</span>
									</div>
								</div>
							</a>
						</div>
					</div>
				</c:forEach>

				<div class="clr"></div>
			</div>
		</div>
	</div> --%>

	<!--festival offoer box-->
	<div class="testimonial_bx">
		<div class="wrapper">
			<section class="regular-cake slider">
				<c:forEach items="${festiveEventList}" var="festEvent"
					varStatus="count">
					<c:set var="td" value="${festEvent.toDate}"></c:set>
					<c:set var="fd" value="${festEvent.fromDate}"></c:set>
					<%
						String dt = (String) pageContext.getAttribute("td");
							String dtfrm = (String) pageContext.getAttribute("fd");
							Date curDate = new Date();
							SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
							Date date = sdf.parse(dt);
							Date frmDate = sdf.parse(dtfrm);

							if (curDate.compareTo(frmDate) >= 0 && curDate.compareTo(date) <= 0) {
								pageContext.setAttribute("show", 1);
							} else {
								pageContext.setAttribute("show", 1);
							}
					%>
					<c:set var="isShow" value="${show}"></c:set>
					<%-- <c:forEach begin="1" end="10" step="1" varStatus="cn"> --%>
					<c:if test="${isShow==1}">
						<div>
							<div class="festival_offer">
								<a
									href="${pageContext.request.contextPath}/showEventBasedCakes/${count.index}"
									title="${festEvent.description}">${festEvent.eventName} <img
									src="${festEventImgUrl}${festEvent.exVar2}" class="lazy"
									data-src="${festEventImgUrl}${festEvent.exVar2}"
									onerror="this.src='${pageContext.request.contextPath}/resources/images/no_img_folder/no-offer-image.jpg'">
								</a>
							</div>
						</div>
					</c:if>
					<%-- </c:forEach> --%>
				</c:forEach>
			</section>
		</div>
	</div>


	<!--new cake box-->
	<c:forEach items="${flavTagStatusList}" var="statusFilter"
		varStatus="count">
		<c:choose>
			<c:when
				test="${statusFilter.filterTypeId==5 && statusFilter.costAffect==1}">
				<div class="find_store">
					<h2 class="sec_title">
						<center>
							${statusFilter.filterName} <span>${statusFilter.filterName}</span>
						</center>
					</h2>
					<div class="wrapper">
						<section class="regular-cake slider">

							<c:forEach items="${prodHeaderList}" var="product"
								varStatus="prodCount">
								<c:choose>
									<c:when
										test="${product.prodStatusId==statusFilter.filterId && product.isHomePageProd==1}">
										<%-- 	<c:when test="${product.prodStatusId==statusFilter.filterId}"> --%>
										<div>
											<div class="cake_one">
												<div class="cake_pic">
													<a
														href="${pageContext.request.contextPath}/showProductDetail/${product.productId}">
														<img src="#"
														data-src="${prodImgUrl}${product.prodImagePrimary}"
														onerror="this.src='${pageContext.request.contextPath}/resources/images/no_img_folder/no-product-image.jpg'"
														class="mobile_fit transition lazy">
													</a>

													<div class="purity_icn">
														<c:choose>
															<c:when test="${product.vegNonvegName eq 'VEG'}">
																<img src="#" class="lazy"
																	data-src="${pageContext.request.contextPath}/resources/images/veg_icn.jpg"
																	alt="">
															</c:when>
															<c:when test="${product.vegNonvegName eq 'NON-VEG'}">
																<img src="#" class="lazy"
																	id="nonveg${product.productId}"
																	data-src="${pageContext.request.contextPath}/resources/images/nonveg_icn.jpg"
																	alt="">
															</c:when>
															<c:otherwise>
																<img src="#" class="lazy"
																	data-src="${pageContext.request.contextPath}/resources/images/veg_icn.jpg"
																	alt="">
																<img src="#" class="lazy"
																	id="nonveg${product.productId}"
																	data-src="${pageContext.request.contextPath}/resources/images/nonveg_icn.jpg"
																	alt="">
															</c:otherwise>
														</c:choose>
													</div>





													<div class="circle_tag active"
														onclick="setLike(${product.productId},${product.isLike})">

														<c:choose>

															<c:when test="${product.isLike==0}">
																<img src="#" class="lazy" id="like${product.productId}"
																	data-src="${pageContext.request.contextPath}/resources/images/heart-1.svg"
																	alt="">
															</c:when>
															<c:when test="${product.isLike==1}">
																<img src="#" class="lazy" id="like${product.productId}"
																	data-src="${pageContext.request.contextPath}/resources/images/heart.svg"
																	alt="">
															</c:when>

														</c:choose>


													</div>



													<div class="cake_prc">
												<div>
																<i class="fa fa-inr cake_prc_detail_iclass"
																	aria-hidden="true"></i>

																<c:set value="${product.defaultPrice}" var="price"></c:set>
																<c:set value="1" var="defaultWt"></c:set>

																<c:choose>

																	<c:when test="${product.rateSettingType == 1}">

																		<c:forEach items="${product.availInWeights}"
																			var="proWt" varStatus="loop" begin="0" end="0">
																			<c:set value="${proWt}" var="defaultWt"></c:set>
																		</c:forEach>

																		<c:set value="${product.defaultPrice * defaultWt}"
																			var="price"></c:set>

																	</c:when>

																	<c:when test="${product.rateSettingType == 2}">

																		<c:forEach items="${product.availInWeights}"
																			var="proWt" varStatus="loop" begin="0" end="0">
																			<c:set value="${proWt}" var="defaultWt"></c:set>
																		</c:forEach>

																		<c:forEach items="${product.prodDetailList}"
																			var="proDetail">

																			<c:choose>
																				<c:when
																					test="${proDetail.flavorId==product.defaultFlavorId and proDetail.qty==defaultWt}">
																					<c:set value="${proDetail.actualRate}" var="price"></c:set>
																				</c:when>
																			</c:choose>
																		</c:forEach>

																	</c:when>


																</c:choose>

																<p class="cake_prc_detail_pclass"
																	id="newPrice${product.productId}">${price} /-</p>

															</div>
													<%-- <i class="fa fa-inr" aria-hidden="true"></i>
													<fmt:formatNumber type="number" groupingUsed="false"
														value="${product.defaultPrice}" maxFractionDigits="0"
														minFractionDigits="0" /> 													
													<p class="per_kg">${product.uomShowName}</p>--%>
													
													<%-- <span class="off_prc"><i class="fa fa-inr"
														aria-hidden="true"></i> <fmt:formatNumber type="number"
															groupingUsed="false" value="${product.defaultPrice}"
															maxFractionDigits="0" minFractionDigits="0" /></span>  --%><span
														class="prc_off"></span>
												</div>

												</div>
												<div class="cake_container">
													<h4 class="cake_nm">
														<a
															href="${pageContext.request.contextPath}/showProductDetail/${product.productId}">${product.productName}</a>
													</h4>
													<div class="cake_dropdown">
														<div class="cake_dropdown_l">


															<c:choose>

																<c:when test="${product.rateSettingType==0}">
																	<!-- <input type="number" id="wt" value="1" max="2" min="0"
																		limit="1" style="text-align: center;"> -->
																	<div class="plus_minus_one">
																		<button type="button" value="" field="quantity"
																			class="qtyminus slide"
																			onclick="setQtyText(${product.productId},0,'${product.prodDetailList}')">
																			<i class="fa fa-minus" aria-hidden="true"></i>
																		</button>
																		<input type="text" id="txtWt${product.productId}"
																			value="1" style="text-align: center;"
																			class="qty slide">
																		<button type="button" value="" field="quantity"
																			onclick="setQtyText(${product.productId},1,'${product.prodDetailList}')"
																			class="qtyplus slide">
																			<i class="fa fa-plus" aria-hidden="true"></i>
																		</button>
																	</div>
																</c:when>

																<c:otherwise>

																	<!-- <div class="custom-select-new1"> -->
																	<div class="small_field">
																		<select class="select-css" id="wt${product.productId}"
																			onchange="setPriceByWtAndFlavour('${product.productId}','${product.rateSettingType}')">
																			<!-- <option value="7">7</option> -->
																			<c:forEach items="${product.availInWeights}"
																				var="prodDetailwt">
																				<option value="${prodDetailwt}">${prodDetailwt}</option>
																			</c:forEach>
																		</select>
																		<!-- </div> -->
																	</div>

																</c:otherwise>

															</c:choose>

															<span class="prod_kgs">${product.uomShowName}</span>

														</div>
														<div class="cake_dropdown_r">


															<div class="radio_1">
																<ul>
																	<c:set var="isVegFound" value="0"></c:set>
																	<c:set var="isNonVegFound" value="0"></c:set>
																	<c:forEach items="${product.isVeg}"
																		var="prodDetailVegNon">


																		<c:forEach items="${flavTagStatusList}"
																			var="vegNonFilter" varStatus="flavorFilterCount">
																			<c:if test="${vegNonFilter.filterTypeId==12}">



																				<c:if
																					test="${vegNonFilter.filterId==prodDetailVegNon}">
																					<c:if test="${vegNonFilter.adminName eq 'VEG'}">
																						<c:set var="isVegFound" value="1"></c:set>
																					</c:if>

																					<c:if test="${vegNonFilter.adminName eq 'NONVEG'}">
																						<c:set var="isNonVegFound" value="1"></c:set>
																					</c:if>
																				</c:if>
																			</c:if>
																		</c:forEach>

																	</c:forEach>



																	<%-- <c:if test="${isVegFound==1}">
																		<li><input type="radio" value="0"
																			id="prod_veg${product.productId}"
																			name="prod_vnv${product.productId}"> <label
																			for="prod_veg${product.productId}"> Veg</label>
																			<div class="check">
																				<div class="inside"></div>
																			</div></li>

																	</c:if>

																	<c:if test="${isNonVegFound==1}">
																		<li><input type="radio" value="1"
																			id="prod_nonveg${product.productId}"
																			name="prod_vnv${product.productId}"> <label
																			for="prod_nonveg${product.productId}"> Non
																				Veg</label>
																			<div class="check">
																				<div class="inside"></div>
																			</div></li>
																	</c:if> --%>

																	<div style="display: none;">
																	<%-- <c:if test="${product.flavourIds!=0}">
																		<select class="select-css"
																			id="flav${product.productId}"
																			onchange="setPriceByWtAndFlavour('${product.productId}','${product.rateSettingType}')">
																			<c:forEach items="${product.flavourIds}"
																				var="prodDetail">

																				<c:forEach items="${flavTagStatusList}"
																					var="flavorFilter" varStatus="flavorFilterCount">

																					<c:if test="${flavorFilter.filterTypeId==4}">

																						<c:choose>
																							<c:when
																								test="${prodDetail==flavorFilter.filterId}">
																								<c:choose>
																									<c:when
																										test="${prodDetail==product.defaultFlavorId}">
																										<option value="${prodDetail}" selected>${flavorFilter.adminName}</option>
																									</c:when>
																									<c:otherwise>
																										<option value="${prodDetail}">${flavorFilter.adminName}</option>
																									</c:otherwise>
																								</c:choose>
																							</c:when>
																							<c:otherwise>

																							</c:otherwise>
																						</c:choose>
																					</c:if>

																				</c:forEach>
																			</c:forEach>
																		</select>
																	</c:if> --%>
																	</div>
																</ul>
																<!-- <ul>
																	<li><input type="radio" id="a-option"
																		name="selector"> <label for="a-option">Veg</label>
																		<div class="check"></div></li>

																	<li><input type="radio" id="b-option"
																		name="selector"> <label for="b-option">Non
																			Veg</label>
																		<div class="check">
																			<div class="inside"></div>
																		</div></li>

																</ul> -->
															</div>
														</div>
														<div class="radio_r">
															<a href="javascript:void(0)"
																onclick="addCart('${product.productId}','${product.rateSettingType}')" title="Add To Cart">
																<i class="fa fa-shopping-cart shop_cart"></i></a>
														</div>
														<div class="clr"></div>
													</div>
													<!-- <div class="cake_radio_row">
														<div class="radio_l">

															<div class="radio_1">
																<ul>
																	<li><input type="radio" id="a-option"
																		name="selector"> <label for="a-option">Veg</label>
																		<div class="check"></div></li>

																	<li><input type="radio" id="b-option"
																		name="selector"> <label for="b-option">Non
																			Veg</label>
																		<div class="check">
																			<div class="inside"></div>
																		</div></li>

																</ul>
															</div>

														</div>
														<div class="radio_r">
															<a href="my-cart.html" class="cart_btn">Add to Cart</a>
														</div>
														<div class="clr"></div>
													</div> -->


													<%-- <div class="cake_radio_row">
														<div class="radio_l">

															<!-- Flavor 25-12-2020 -->

															<div>
																<i class="fa fa-inr cake_prc_detail_iclass"
																	aria-hidden="true"></i>

																<c:set value="${product.defaultPrice}" var="price"></c:set>
																<c:set value="1" var="defaultWt"></c:set>

																<c:choose>

																	<c:when test="${product.rateSettingType == 1}">

																		<c:forEach items="${product.availInWeights}"
																			var="proWt" varStatus="loop" begin="0" end="0">
																			<c:set value="${proWt}" var="defaultWt"></c:set>
																		</c:forEach>

																		<c:set value="${product.defaultPrice * defaultWt}"
																			var="price"></c:set>

																	</c:when>

																	<c:when test="${product.rateSettingType == 2}">

																		<c:forEach items="${product.availInWeights}"
																			var="proWt" varStatus="loop" begin="0" end="0">
																			<c:set value="${proWt}" var="defaultWt"></c:set>
																		</c:forEach>

																		<c:forEach items="${product.prodDetailList}"
																			var="proDetail">

																			<c:choose>
																				<c:when
																					test="${proDetail.flavorId==product.defaultFlavorId and proDetail.qty==defaultWt}">
																					<c:set value="${proDetail.actualRate}" var="price"></c:set>
																				</c:when>
																			</c:choose>
																		</c:forEach>

																	</c:when>


																</c:choose>

																<p class="cake_prc_detail_pclass"
																	id="newPrice${product.productId}">${price}</p>

															</div>


														</div>
														<div class="radio_r">
															<a href="javascript:void(0)"
																onclick="addCart('${product.productId}','${product.rateSettingType}')"
																class="cart_btn">Add to Cart</a>
														</div>
														<div class="clr"></div>
													</div> --%>

												</div>

											</div>
										</div>
										<!-- End of div cake one -->
									</c:when>
									<c:otherwise>

									</c:otherwise>
								</c:choose>
							</c:forEach>
						</section>
						<div class="more_cakes">
							<a
								href="${pageContext.request.contextPath}/moreCakeStatusWise/${statusFilter.filterId}">More
								${statusFilter.filterName}</a>
						</div>
					</div>
				</div>
				<!--  End of Find_Store Div -->
			</c:when>
			<c:otherwise>

			</c:otherwise>
		</c:choose>

	</c:forEach>



	<!--testimonial-box-->
	<div class="testimonial_bx">
		<h2 class="sec_title">
			<center>
				Our Testimonials <span>Customer Reviews regarding to our Shop</span>
			</center>
		</h2>

		<div class="wrapper">
			<section class="regular slider">
				<c:forEach items="${testMonialList}" var="testmoni"
					varStatus="count">
					<div>
						<div class="testimonial_one">
							<i class="fa fa-quote-left" aria-hidden="true"></i>
							<p class="testimoial_txt">${testmoni.messages}</p>

							<div class="testimonial_nm">
								<img src="${TestimonialImgUrl}${testmoni.images}"
									onerror="this.src='${pageContext.request.contextPath}/resources/images/no_img_folder/no-testimonial-picture.jpg'">
								<h2 class="testimonial_date">
									${testmoni.name} <span>${testmoni.designation}</span>
									<!--  <span>Location: location</span> -->
								</h2>
							</div>
						</div>
					</div>
				</c:forEach>
			</section>
		</div>

	</div>

	<!--find-store-->
	<div class="find_store">
		<div class="wrapper">
			<div class="store_banner"
				style="background: url(${pageContext.request.contextPath}/resources/images/add_banner.jpg) no-repeat center top; background-size: cover;">
				<div class="store_content">
					<div class="visit_cont">
						<div class="experiance_bx">
							<div class="experiance_bor">
								<h2 class="visit_title">Visit &amp; Experience Our Service
									in Your City</h2>
								<a href="#" class="find_btn">Find Stores <i
									class="fa fa-angle-right" aria-hidden="true"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!--strip-->
	<div class="type_strip">
		<div class="wrapper">
			<ul class="strip_divid">
				<li>
					<div class="strip_payment">
						<img src="#" class="lazy"
							data-src="${pageContext.request.contextPath}/resources/images/secure_icn.png"
							alt=""> 100% Secure Payments <span>All major credit
							&amp; debit cards accepted</span>
					</div>
				</li>
				<li>
					<div class="strip_payment extra_padd">
						<img src="#" class="lazy"
							data-src="${pageContext.request.contextPath}/resources/images/customer.png"
							alt=""> 3,000,000 <span>Customers across the world</span>
					</div>
				</li>
				<li>
					<div class="strip_payment extra_padd">
						<img src="#" class="lazy"
							data-src="${pageContext.request.contextPath}/resources/images/gifts.png"
							alt=""> 2 Million+ Gift <span>boxes delivered
							worldwide</span>
					</div>
				</li>
			</ul>
		</div>
	</div>

	<!-- bottom -->
	<jsp:include page="/WEB-INF/views/include/bottomMenu.jsp"></jsp:include>


	<script type="text/javascript">
		function changeWtFlavor(productId) {
			try{
			var selectWt = document.getElementById("wt" + productId).value;
			var selectFlav = 0;
			try {
				selectFlav = document.getElementById("flav" + productId).value;
			} catch (e) {
				selectFlav = 0;
			}
			if (selectFlav == "" || isNaN(selectFlav) || selectFlav == null) {
				selectFlav = 0;
			}
			var isVeg = $('input[name="prod_vnv' + productId + '"]:checked')
					.val();
			var dataList = '${sessionScope.dataList}';
			var data = $.parseJSON(dataList);
			var selectVegNon = "Veg";
			var prodHead = data.feProductHeadList;
			var prodMaster;
			for (var h = 0; h < prodHead.length; h++) {
				if (parseInt(productId) == parseInt(prodHead[h].productId)) {
					prodMaster = prodHead[h];
					if (typeof (isVeg) == "undefined") {
						selectVegNon = prodMaster.defaultVegNonvegName;
					} else if (parseInt(isVeg) == 1) {
						selectVegNon = "NonVeg";
					} else {
						selectVegNon = "Veg";
					}
					break;
				}
			}//end of prodHead For H
			var prodDetail = prodMaster.prodDetailList;
			for (var d = 0; d < prodDetail.length; d++) {
				if (parseInt(prodMaster.defaultShapeId) == parseInt(prodDetail[d].shapeId)) {
					if (parseInt(prodDetail[d].flavorId) == parseInt(selectFlav)) {
						if (prodDetail[d].vegNonvegName == selectVegNon) {
							//Calc Price;
							if (parseFloat(selectWt) == parseFloat(prodDetail[d].qty)) {

								var qty = 1;
								document.getElementById("cake_prc" + productId).innerHTML = ""
										+ prodDetail[d].actualRate;
								actualRate = prodDetail[d].actualRate;
								var priceDiff = parseFloat(prodDetail[d].displayRate)
										- parseFloat(actualRate);
								offPer = (parseFloat(priceDiff)
										/ parseFloat(prodDetail[d].displayRate) * 100);
								//document.getElementById("prc_off" + productId).innerHTML = ""+priceDiff.toFixed(2);
								document.getElementById('off_prc' + productId).innerHTML = "<i class='fa fa-inr' aria-hidden='true'>"
										+ priceDiff.toFixed(2) + "</i>";
								//document.getElementById('off_prc'+productId).innerHTML = "<i class='fa fa-inr' aria-hidden='true'>414</i>";
								document.getElementById("prc_off" + productId).innerHTML = ""
										+ offPer.toFixed(2);
								break;
							}
							//alert("Do calc");
						} else {
							continue;
						}
					} else {
						continue;
					}
				} else {
					continue;
				}
			}//end of For prodDetailList pd
			}catch (e) {
				
			}
		}//end of Function changeWtFlavor
	</script>
	<!-- <script type="text/javascript">
		function addToCartClick(productId) {
			alert("In addToCartClick " + productId);
			var selectWt = document.getElementById("wt" + productId).value;

			var selectFlav = 0;
			try {
				selectFlav = document.getElementById("flav" + productId).value;
			} catch (e) {
				selectFlav = 0;
			}
			if (selectFlav == "" || isNaN(selectFlav) || selectFlav == null) {
				selectFlav = 0;
			}

			var isVeg = $('input[name="prod_vnv' + productId + '"]:checked').val();
			var dataList = '${sessionScope.dataList}';
			var data = $.parseJSON(dataList);
			var selectVegNon = "Veg";
			var prodHead = data.feProductHeadList;
			var prodMaster;
			for (var h = 0; h < prodHead.length; h++) {
				if (parseInt(productId) == parseInt(prodHead[h].productId)) {
					prodMaster = prodHead[h];
					if (typeof (isVeg) == "undefined") {
						selectVegNon = prodMaster.defaultVegNonvegName;
					} else if (parseInt(isVeg) == 1) {
						selectVegNon = "NonVeg";
					} else {
						selectVegNon = "Veg";
					}
					break;
				}
			}//end of prodHead For H
			var prodDetail = prodMaster.prodDetailList;
			for (var d = 0; d < prodDetail.length; d++) {
				//alert("OKkk");
				if (parseInt(prodMaster.defaultShapeId) == parseInt(prodDetail[d].shapeId)) {
					if (parseInt(prodDetail[d].flavorId) == parseInt(selectFlav)) {
						if (prodDetail[d].vegNonvegName == selectVegNon) {
							//Calc Price;
							if (parseFloat(selectWt) == parseFloat(prodDetail[d].qty)) {
								//alert(prodDetail[d].configDetailId);
								var qty = 1;
								document.getElementById("cake_prc" + productId).innerHTML = ""
										+ prodDetail[d].actualRate;
								actualRate = prodDetail[d].actualRate;
								var priceDiff = parseFloat(prodDetail[d].displayRate)
										- parseFloat(actualRate);
								offPer = (parseFloat(priceDiff)
										/ parseFloat(prodDetail[d].displayRate) * 100);

								taxableAmt = actualRate;

								cgstAmt = (parseFloat(actualRate) * parseFloat(prodMaster.cgstPer)) / 100;
								sgstAmt = (parseFloat(actualRate) * parseFloat(prodMaster.sgstPer)) / 100;
								igstAmt = (parseFloat(actualRate) * parseFloat(prodMaster.igstPer)) / 100;

								taxAmt = (cgstAmt + sgstAmt + igstAmt)
										.toFixed(2);
								totalAmt = (parseFloat(taxableAmt)).toFixed(2);

								if (sessionStorage.getItem("cartValue") == null) {
									var table = [];
									sessionStorage.setItem("cartValue", JSON
											.stringify(table));
								}

								var cartValue = sessionStorage
										.getItem("cartValue");
								var table = $.parseJSON(cartValue);

								table.push({
									orderDetailId : 0,
									orderId : 0,
									itemId : prodMaster.productId,
									hsnCode : prodMaster.hsnCode,
									qty : 1,
									mrp : prodDetail[d].displayRate,
									rate : prodDetail[d].actualRate,
									taxableAmt : taxableAmt,
									cgstPer : prodMaster.cgstPer,
									sgstPer : prodMaster.sgstPer,
									igstPer : prodMaster.igstPer,
									cgstAmt : cgstAmt,
									sgstAmt : sgstAmt,
									igstAmt : igstAmt,
									discAmt : 0,
									taxAmt : taxAmt,
									totalAmt : totalAmt,
									delStatus : 1,
									remark : '',
									exInt1 : prodDetail[d].configDetailId,
									exInt2 : prodDetail[d].flavorId,
									exInt3 : prodDetail[d].isVeg,
									exInt4 : prodDetail[d].shapeId,
									exVar1 : prodMaster.productName,
									exVar2 : '',
									exVar3 : '',
									exVar4 : '',
									exFloat1 : 1,
									exFloat2 : 1,
									exFloat3 : 1,
									exFloat4 : 1,
									weight : selectWt,
									veg : selectVegNon,
									spInst : "na spi",
									msgonCake : 'na msgcake'
								});
								//alert(JSON.stringify(table.spInst));
								sessionStorage.setItem("cartValue", JSON
										.stringify(table));
								appendCartData();
								break;
							}
							//alert("Do calc");
						} else {
							continue;
						}
					} else {
						continue;
					}
				} else {
					continue;
				}

			}//end of For prodDetailList pd

		}//end of Function addToCartClick
		</script> -->
	<script type="text/javascript">
		//Not used here its from header.jsp
		function appendCartData_OLD_NO_USE() {

			if (sessionStorage.getItem("allItemList") == null) {
				var table = [];
				sessionStorage.setItem("allItemList", JSON.stringify(table));
			}

			if (sessionStorage.getItem("cartValue") == null) {
				var table = [];
				sessionStorage.setItem("cartValue", JSON.stringify(table));
			}

			var cartValue = sessionStorage.getItem("cartValue");
			var table = $.parseJSON(cartValue);

			var allItemList = sessionStorage.getItem("allItemList");
			var allItemArr = $.parseJSON(allItemList);

			$("#item_cart_list").html('');
			$("#proc_chkout").html('');
			$("#cart_item_count").html('');

			var subtotal = 0;
			var prodIdStr = "";
			for (var j = 0; j < allItemArr.length; j++) {
				for (var i = 0; i < table.length; i++) {

					if (table[i].itemId == allItemArr[j].productId) {
						prodIdStr = prodIdStr + "," + allItemArr[j].productId;
						//alert(i);
						subtotal = (parseFloat(subtotal) + parseFloat(table[i].totalAmt))
								.toFixed(2);
						
						
						var prodName="";
						
						if(table[i].rateSettingType == 0){
							prodName=table[i].exVar1;
						}else {
							
							prodName=table[i].exVar1+" Flavour - "+table[i].flvName+" Weight - "+table[i].weight;
							
						}
						
						
						$("#item_cart_list")
								.append(
										'<div class="like_one">'
												+ '<div class="like_pic">'
												+ '<img src="${prodImgUrl}'+allItemArr[j].prodImagePrimary+'" class="lazy"'+
				'data-src="${prodImgUrl}'+allItemArr[j].prodImagePrimary+'"'+
				'alt="">'
												+ '</div>'
												+ '<div class="like_cont">'
												+ '<h4 class="like_cake_nm">'
												+ prodName
												+ '</h4>'
												+ '<p class="like_prc">Rs.'
												+ table[i].totalAmt
												+ '</p>'
												+ '<div class="like_quant">'
												+ '<span>Qty.</span>'
												+ '<form id="myform" method="POST" action="#">'
												+ '<input type="button" value="-" onclick="setQty('
												+ table[i].itemId
												+ ','
												+ i
												+ ','
												+ table[i].qty
												+ ',0)" class="qtyminus"'
												+ 'field="quantity"/><input type="text" id="prod_quantity'+table[i].itemId+'" name="prod_quantity'+table[i].itemId+'"'+
						'value="'+table[i].qty+'" class="qty" /> <input type="button" onclick="setQty('
												+ table[i].itemId
												+ ','
												+ i
												+ ','
												+ table[i].qty
												+ ',1)" value="+"'
												+ 'class="qtyplus" field="quantity"/>'
												+ '</form>'
												+ '</div>'
												+ '</div>'
												+ '<div class="clr"></div>'
												+ '</div>')

					}//IF
				}//End of For loop 2
			}//End of loop 1
			document.getElementById("cart_item_count").innerHTML = ""
					+ table.length;
			$("#proc_chkout")
					.append(
							'<div class="proc_chkout">'
									+ '<span>Total : Rs.'
									+ subtotal
									+ '/- </span> <a href="${pageContext.request.contextPath}/checkout/'+prodIdStr+'">Proceed'
									+ ' to Checkout</a>' + '</div>')

		}
		</script>
	<script type="text/javascript">
		
		function setQty(productId, position, curQty, buttonType) {
			//setQty('+table[i].itemId+','+i+','+table[i].qty+',0)"
			//prod_quantity+productId;
			var ischanged = 0;

			if (parseInt(buttonType) == 0 && parseInt(curQty) > 1) {
				//Its Minus call;
				//alert("If")
				curQty = parseInt(curQty) - 1;
				ischanged = 1;
			} else if (parseInt(buttonType) == 1) {
				//Its Plus;
				//alert("Else")
				curQty = parseInt(curQty) + 1;
				ischanged = 1;
			}

			/* else {

				if (sessionStorage.getItem("cartValue") == null) {
					var table = [];
					sessionStorage.setItem("cartValue", JSON.stringify(table));
				}

				var cartValue = sessionStorage.getItem("cartValue");
				var table = $.parseJSON(cartValue);

				var newCartVal = [];

				for (var i = 0; i < table.length; i++) {
					if (productId != table[i].itemId) {
						newCartVal.push(table[i]);
					}
				}

				sessionStorage.setItem("cartValue", JSON.stringify(newCartVal));
				appendCartData();
			} */

			if (parseInt(ischanged) == 1) {
				var cartValue = sessionStorage.getItem("cartValue");
				var table = $.parseJSON(cartValue);
				table[position].qty = curQty;

				var qty = parseFloat(curQty);
				var taxableAmt = parseFloat(table[position].rate)
						* parseFloat(qty).toFixed(2);
				var cgstAmt = (parseFloat(table[position].rate)
						* parseFloat(qty) * parseFloat(table[position].cgstPer)) / 100;
				var sgstAmt = (parseFloat(table[position].rate)
						* parseFloat(qty) * parseFloat(table[position].sgstPer)) / 100;
				var igstAmt = (parseFloat(table[position].rate)
						* parseFloat(qty) * parseFloat(table[position].igstPer)) / 100;

				var taxAmt = (cgstAmt + sgstAmt + igstAmt).toFixed(2);
				var totalAmt = parseFloat(taxableAmt).toFixed(2);

				table[position].taxableAmt = taxableAmt;
				table[position].cgstAmt = cgstAmt;
				table[position].sgstAmt = sgstAmt;
				table[position].igstAmt = igstAmt;
				table[position].taxAmt = taxAmt;
				table[position].totalAmt = totalAmt;
				console.log(table);
				sessionStorage.setItem("cartValue", JSON.stringify(table));
				appendCartData();
			}//end of If ischanged==1
		}
		function clearData() {
			sessionStorage.clear();
		}
		//appendCartData(); // Onload call.
	</script>


	<!--cart-sidepanel-->
	<script type="text/javascript">
		function openNav2() {
			document.getElementById("mySidepanel2").style.width = "300px";
		}
		function closeNav2() {
			document.getElementById("mySidepanel2").style.width = "0";
		}
	</script>
	<!--main-menu-js-->
	<script>
		function openNav1() {
			document.getElementById("myNav").style.height = "100%";
		}
		function closeNav1() {
			document.getElementById("myNav").style.height = "0%";
		}
	</script>
	<!--menuzord -->
	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery("#menuzord").menuzord({
				align : "left"
			});
		});
	</script>
	<!--menuzord-->
	<!--slick slider-->
	<script type="text/javascript">
		$(document).on('ready', function() {
			$(".regular").slick({
				dots : true,
				infinite : true,
				slidesToShow : 3,
				slidesToScroll : 1,
				autoplay : true,
				responsive : [ {
					breakpoint : 1024,
					settings : {
						slidesToShow : 3,
						slidesToScroll : 1,
						infinite : true,
						dots : true
					}
				}, {
					breakpoint : 768,
					settings : {
						slidesToShow : 2,
						slidesToScroll : 1
					}
				}, {
					breakpoint : 480,
					settings : {
						slidesToShow : 1,
						slidesToScroll : 1
					}
				} ]
			});
			$(".regular-cake").slick({
				dots : true,
				infinite : true,
				slidesToShow : 4,
				slidesToScroll : 1,
				autoplay : true,
				
				responsive : [ {
					breakpoint : 1024,
					settings : {
						slidesToShow : 3,
						slidesToScroll : 1,
						infinite : true,
						dots : true
					}
				}, {
					breakpoint : 768,
					settings : {
						slidesToShow : 2,
						slidesToScroll : 1
					}
				}, {
					breakpoint : 480,
					settings : {
						slidesToShow : 1,
						slidesToScroll : 1
					}
				} ]
			});
		});
	</script>
	<script type="text/javascript">
		/*Dropdown Menu*/
		$('.dropdown').click(function() {
			$(this).attr('tabindex', 1).focus();
			$(this).toggleClass('active');
			$(this).find('.dropdown-menu').slideToggle(300);
		});
		$('.dropdown').focusout(function() {
			$(this).removeClass('active');
			$(this).find('.dropdown-menu').slideUp(300);
		});
		$('.dropdown .dropdown-menu li').click(
				function() {
					$(this).parents('.dropdown').find('span').text(
							$(this).text());
					$(this).parents('.dropdown').find('input').attr('value',
							$(this).attr('id'));
				});
		/*End Dropdown Menu*/
		$('.dropdown2').click(function() {
			$(this).attr('tabindex', 1).focus();
			$(this).toggleClass('active');
			$(this).find('.dropdown-menu').slideToggle(300);
		});
		$('.dropdown2').focusout(function() {
			$(this).removeClass('active');
			$(this).find('.dropdown-menu').slideUp(300);
		});
		$('.dropdown2 .dropdown-menu li').click(
				function() {
					$(this).parents('.dropdown2').find('span').text(
							$(this).text());
					$(this).parents('.dropdown2').find('input').attr('value',
							$(this).attr('id'));
				});
	</script>
	<script type="text/javascript">
		document
				.addEventListener(
						"DOMContentLoaded",
						function() {
							var lazyloadImages;
							if ("IntersectionObserver" in window) {
								lazyloadImages = document
										.querySelectorAll(".lazy");
								var imageObserver = new IntersectionObserver(
										function(entries, observer) {
											entries
													.forEach(function(entry) {
														if (entry.isIntersecting) {
															var image = entry.target;
															image.src = image.dataset.src;
															image.classList
																	.remove("lazy");
															imageObserver
																	.unobserve(image);
														}
													});
										});

								lazyloadImages.forEach(function(image) {
									imageObserver.observe(image);
								});
							} else {
								var lazyloadThrottleTimeout;
								lazyloadImages = document
										.querySelectorAll(".lazy");

								function lazyload() {
									if (lazyloadThrottleTimeout) {
										clearTimeout(lazyloadThrottleTimeout);
									}
									lazyloadThrottleTimeout = setTimeout(
											function() {
												var scrollTop = window.pageYOffset;
												lazyloadImages
														.forEach(function(img) {
															if (img.offsetTop < (window.innerHeight + scrollTop)) {
																img.src = img.dataset.src;
																img.classList
																		.remove('lazy');
															}
														});
												if (lazyloadImages.length == 0) {
													document
															.removeEventListener(
																	"scroll",
																	lazyload);
													window.removeEventListener(
															"resize", lazyload);
													window
															.removeEventListener(
																	"orientationChange",
																	lazyload);
												}
											}, 20);
								}
								document.addEventListener("scroll", lazyload);
								window.addEventListener("resize", lazyload);
								window.addEventListener("orientationChange",
										lazyload);
							}
						})
</script>
	<script type="text/javascript">
		function openProductListPageByTags(tagIds) {

			if (sessionStorage.getItem("allTagList") == null) {
				var table = [];
				sessionStorage.setItem("allTagList", JSON.stringify(table));
			}

			var allTagList = sessionStorage.getItem("allTagList");
			var allTags = $.parseJSON(allTagList);
			//alert(allTags)

			var idArray = tagIds.split(",");

			var selTags = [];

			for (var i = 0; i < idArray.length; i++) {
				for (var j = 0; j < allTags.length; j++) {

					if (idArray[i] == allTags[j].filterId) {
						selTags.push(allTags[j].filterName);
					}

				}
			}

			sessionStorage.setItem("selTags", JSON.stringify(selTags));

			//alert(tagIds)
			window.open("${pageContext.request.contextPath}/products/0",
					"_self");

		}
		</script>
	<script type="text/javascript">
		
		function setQtyText(id, type) {

			/* type  :  0 - minus,  1 - plus */
			
			var wt=document.getElementById("txtWt"+id).value;
		//alert(id+"    "+type+ "     "+wt)
		
		//alert(detailList);
			
			if(type==0){
			
				var newWt=wt+1;
				if(wt>1 && wt<=10){
					wt=parseInt(wt)-1;
				}
				
			}
			
			else if(type==1){
				if(wt>=1 && wt<10){
					wt=parseInt(wt)+1;
				}
			}
			
			document.getElementById("txtWt"+id).value=wt;
			
			
			if (sessionStorage.getItem("allItemList") == null) {
				var table = [];
				sessionStorage.setItem("allItemList", JSON.stringify(table));
			}

			var allItemList = sessionStorage.getItem("allItemList");
			var allItemArr = $.parseJSON(allItemList);

			var rate=0;
			
			for(var i=0;i<allItemArr.length;i++){
				
				if(allItemArr[i].productId==id){
			
					rate=parseFloat(allItemArr[i].prodDetailList[0].actualRate);
				}
				
			}
			
			rate=rate*wt;
			
			//27-04document.getElementById("newPrice"+id).innerHTML=rate.toFixed(1);
			

		}
		
		</script>
	<script type="text/javascript">
		
		function setPriceByWtAndFlavour(id,type) {
			
			//alert(id+"      "+type)
			
			var selectWt = document.getElementById("wt" + id).value;
			var selectFlav = 0;
			try {
				selectFlav = document.getElementById("flav" + id).value;
			} catch (e) {
				selectFlav = 0;
			}
			if (selectFlav == "" || isNaN(selectFlav) || selectFlav == null) {
				selectFlav = 0;
			}
			
			//alert(selectWt+"          "+selectFlav)
			
			if (sessionStorage.getItem("allItemList") == null) {
				var table = [];
				sessionStorage.setItem("allItemList", JSON.stringify(table));
			}

			var allItemList = sessionStorage.getItem("allItemList");
			var allItemArr = $.parseJSON(allItemList);

			var rate=0;
			
			for(var i=0;i<allItemArr.length;i++){
				if(allItemArr[i].productId==id){
					rate=parseFloat(allItemArr[i].defaultPrice);
				}
			}
			
			for(var i=0;i<allItemArr.length;i++){
				if(allItemArr[i].productId==id){
					for(var j=0;j<allItemArr[i].prodDetailList.length;j++){
						if(allItemArr[i].prodDetailList[j].flavorId==selectFlav && type==1){
							rate=parseFloat(allItemArr[i].prodDetailList[j].actualRate);
							break;
						}else if(allItemArr[i].prodDetailList[j].flavorId==selectFlav && allItemArr[i].prodDetailList[j].qty==selectWt && type==2){
							rate=parseFloat(allItemArr[i].prodDetailList[j].actualRate);
							break;
						}
					}
				}
			}
			
			if(type==1){
				rate=rate*parseFloat(selectWt);
			}
			
			document.getElementById("newPrice"+id).innerHTML=rate.toFixed(1);
			
		}
		
		</script>
	<script type="text/javascript">
		function addCart(id,type) {
			
			
			
			var selectFlav = 0;
			
			var selectWt = 0;
			
			var selFlvName ="";
			
			if(type == 0){
				selectWt = document.getElementById("txtWt"+id).value;	
				//alert("selectWt" +selectWt)
			}else if(type == 1 || type == 2){
				selectWt = document.getElementById("wt" + id).value;
				
				try {
					selectFlav = document.getElementById("flav" + id).value;
					
					var docFlv = document.getElementById("flav" + id);
					selFlvName = docFlv.options[docFlv.selectedIndex].text;
					
				} catch (e) {
					selectFlav = 0;
				}
				if (selectFlav == "" || isNaN(selectFlav) || selectFlav == null) {
					selectFlav = 0;
				}
			}
			
			
				
				
				var prodMaster;
				
				if (sessionStorage.getItem("allItemList") == null) {
					var table = [];
					sessionStorage.setItem("allItemList", JSON.stringify(table));
				}

				var allItemList = sessionStorage.getItem("allItemList");
				var prodHead = $.parseJSON(allItemList);
				
				//alert("dfdfd "+prodHead )
				
				
				for (var h = 0; h < prodHead.length; h++) {
					if (parseInt(id) == parseInt(prodHead[h].productId)) {
						prodMaster = prodHead[h];
						break;
					}
				}
				
				var prodDetail = prodMaster.prodDetailList;
				//alert(prodDetail)
				
				var actualRate=0;
				var calRate=0;
				var displayRate=0;
				var configDetailId=0;
				var flvId=0;
				var isVeg=0;
				var shapeId=0;
				var flvName=selFlvName;
				
				var qty = 1;
				
				var uniq = (new Date()).getTime();
				//alert(uniq)
						
				 for (var d = 0; d < prodDetail.length; d++) {
					
					if(type == 0){
						
						qty=selectWt;
						
						calRate=prodDetail[d].actualRate*selectWt;
						actualRate=prodDetail[d].actualRate;
						displayRate=prodDetail[d].displayRate;
						configDetailId=prodDetail[d].configDetailId;
						flvId=prodDetail[d].flavorId;
						isVeg=prodDetail[d].isVeg;
						shapeId=prodDetail[d].shapeId;
						
						break;
							
					}else if(type == 1){
						
						if (parseInt(prodDetail[d].flavorId) == parseInt(selectFlav)) {
							
							
							//alert("Shape = "+parseInt(prodDetail[d].shapeId)+"             Flv = "+parseInt(selectFlav))
							
							//alert("1  - "+prodDetail[d].configDetailId)
							
							calRate=prodDetail[d].actualRate*selectWt;
							actualRate=prodDetail[d].actualRate;
							displayRate=prodDetail[d].displayRate;
							configDetailId=prodDetail[d].configDetailId;
							flvId=prodDetail[d].flavorId;
							isVeg=prodDetail[d].isVeg;
							shapeId=prodDetail[d].shapeId;
							
							break;

						}
						
					} else if(type == 2){
						
						if (parseInt(prodDetail[d].flavorId) == parseInt(selectFlav) && parseFloat(selectWt) == parseFloat(prodDetail[d].qty)) {
							
							calRate=prodDetail[d].actualRate;
							actualRate=prodDetail[d].actualRate;
							displayRate=prodDetail[d].displayRate;
							configDetailId=prodDetail[d].configDetailId;
							flvId=prodDetail[d].flavorId;
							isVeg=prodDetail[d].isVeg;
							shapeId=prodDetail[d].shapeId;
							
							break;

						}
						
					} 

				}
				 
				
				
				
				var priceDiff = parseFloat(displayRate)
						- parseFloat(actualRate);
				
				offPer = (parseFloat(priceDiff)
						/ parseFloat(displayRate) * 100);

				taxableAmt = calRate;

				cgstAmt = ((calRate) * parseFloat(prodMaster.cgstPer)) / 100;
				sgstAmt = ((calRate) * parseFloat(prodMaster.sgstPer)) / 100;
				igstAmt = ((calRate) * parseFloat(prodMaster.igstPer)) / 100;

				taxAmt = (cgstAmt + sgstAmt + igstAmt)
						.toFixed(2);
				
				totalAmt = (parseFloat(taxableAmt)).toFixed(2);

				if (sessionStorage.getItem("cartValue") == null) {
					var table = [];
					sessionStorage.setItem("cartValue", JSON
							.stringify(table));
				}

				var cartValue = sessionStorage
						.getItem("cartValue");
				var table = $.parseJSON(cartValue);
				//alert("actualRate" +actualRate)
				if(type==0){
					calRate=actualRate;
				}
				
				
				if (sessionStorage.getItem("cartValue") == null) {
					var table = [];
					sessionStorage.setItem("cartValue", JSON.stringify(table));
				}

				var cartValue = sessionStorage.getItem("cartValue");
				var cartArray = $.parseJSON(cartValue);
				
				var imgFile="";
				var imgName="";
				
			
				
				var index=0,itemFound=0;
				
			
				
				for(var i=0; i<cartArray.length;i++){
					
					//alert(selectWt+"      "+cartArray[i].qty+"         Type - "+type)
					
					if(configDetailId==cartArray[i].exInt1 && type==0){
						index=i;
						itemFound=1;
						imgFile : cartArray[i].imgFile;
						imgName : cartArray[i].imgName;
						break;
					}else if(selectWt==cartArray[i].weight && configDetailId==cartArray[i].exInt1){
						//alert("asasas")
						index=i;
						itemFound=1;
						imgFile : cartArray[i].imgFile;
						imgName : cartArray[i].imgName;
						break;
					}
					/* else if(configDetailId==cartArray[i].exInt1){
						index=i;
						itemFound=1;
						break;
					} */
				}
				
				
				var obj={
						uniqueId : uniq,
						orderDetailId : 0,
						orderId : 0,
						itemId : prodMaster.productId,
						hsnCode : prodMaster.hsnCode,
						qty : qty,
						mrp : displayRate,
						rate : calRate,
						taxableAmt : taxableAmt,
						cgstPer : prodMaster.cgstPer,
						sgstPer : prodMaster.sgstPer,
						igstPer : prodMaster.igstPer,
						cgstAmt : cgstAmt,
						sgstAmt : sgstAmt,
						igstAmt : igstAmt,
						discAmt : 0,
						taxAmt : taxAmt,
						totalAmt : totalAmt,
						delStatus : 1,
						remark : '',
						exInt1 : configDetailId,
						exInt2 : flvId,
						exInt3 : isVeg,
						exInt4 : shapeId,
						exVar1 : prodMaster.productName,
						exVar2 : '',
						exVar3 : '',
						exVar4 : '',
						exFloat1 : 1,
						exFloat2 : 1,
						exFloat3 : 1,
						exFloat4 : 1,
						weight : selectWt,
						veg : "",
						rateSettingType : type,
						flvName : flvName,
						imgFile : imgFile,
						imgName : imgName,
						spInst : "NA",
						msgonCake : 'NA'
						
					}
				
				if(itemFound==1){
					table[index]=obj;
				}else{
					table.push(obj);	
				}
				
				sessionStorage.setItem("cartValue", JSON
						.stringify(table));
				appendCartData();
				
					openNav();
				  	setTimeout(function(){ closeNav(); }, 4000);
				 
		} 
		
		
		
		
		
	</script>
	<script type="text/javascript">
	function setLike(id,isLike) {
		
		if(parseInt(isLike)==0){
			document.getElementById("like"+id).src = "${pageContext.request.contextPath}/resources/images/heart.svg";
		}else{
			document.getElementById("like"+id).src = "${pageContext.request.contextPath}/resources/images/heart-1.svg";
		}
		
		$.getJSON(
				'${setLikeOrDislike}',
				{
					prodId : id,
					ajax : 'true'
				},
				function(data) {
					//alert(JSON.stringify(data));
					
					if(data.msg ==1){
						document.getElementById("like"+id).src = "${pageContext.request.contextPath}/resources/images/heart.svg";
						
					}else{
						document.getElementById("like"+id).src = "${pageContext.request.contextPath}/resources/images/heart-1.svg";
						
					}
					setLikeCount(data.statusText);
				});
		
	}
	</script>






</body>
</html>
